spring.application.name=email

server.port=8082

# Postgres sistema operacional
#spring.datasource.url=jdbc:postgresql://localhost:5432/microservice-email
#Postgres docker
spring.datasource.url=jdbc:postgresql://db:5432/microservice-email
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

# Endereço e  fila do RabbitMQ
spring.rabbitmq.addresses=#Endereço Rabbit
broker.queue.email.name= #Fila rabbit


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= adicionar email 
spring.mail.password= adicionar senha de aplicativo gmail conta
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details = always

management.metrics.enable.all=true