spring.application.name=email

server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/microservice-email}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:}
broker.queue.email.name=${RABBITMQ_EMAIL_QUEUE:}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
management.metrics.enable.all=true
